import hashlib
from time import perf_counter

from app.agent.answer_publisher import AnswerPublisher
from app.application.run_event_recorder import RunEventRecorder
from app.domain.contracts import RetrievalPort
from app.domain.enums import EvidenceLevel
from app.domain.models import AnswerResponse, Claim, RunContext, ToolEvent
from app.retrieval.agentic_retrieval import retrieval_trace_event_detail


class OfflineAgentRuntime:
    """Deterministic runtime for tests, demos, and replay without a model key."""

    def __init__(
        self,
        retrieval: RetrievalPort,
        publisher: AnswerPublisher | None = None,
        event_recorder: RunEventRecorder | None = None,
    ) -> None:
        self._retrieval = retrieval
        self._publisher = publisher or AnswerPublisher()
        self._event_recorder = event_recorder

    async def run(self, user_input: str, context: RunContext) -> AnswerResponse:
        started = perf_counter()
        input_hash = hashlib.sha256(user_input.encode()).hexdigest()
        try:
            bundle = await self._retrieval.retrieve(user_input, context, top_k=5)
        except Exception as exc:
            if self._event_recorder is not None:
                await self._event_recorder.record_tool(
                    context.run_id,
                    ToolEvent(
                        tool_name="search_knowledge",
                        input_hash=input_hash,
                        output_summary=type(exc).__name__,
                        success=False,
                        duration_ms=int((perf_counter() - started) * 1_000),
                    ),
                )
            raise
        if self._event_recorder is not None:
            await self._event_recorder.record_tool(
                context.run_id,
                ToolEvent(
                    tool_name="search_knowledge",
                    input_hash=input_hash,
                    output_summary=(
                        f"evidence_count={len(bundle.evidence)},"
                        f"rounds={len(bundle.trace.get('rounds', []))},"
                        f"stop={bundle.trace.get('stop_reason', 'pipeline_complete')}"
                    ),
                    detail=retrieval_trace_event_detail(bundle.trace),
                    duration_ms=int((perf_counter() - started) * 1_000),
                ),
            )
        if not bundle.evidence:
            return AnswerResponse(
                answer_markdown="No evidence was found for this task.",
                confidence=EvidenceLevel.INSUFFICIENT,
                limitations=["The connected knowledge sources returned no evidence."],
                followup_queries=[user_input],
            )

        citations = bundle.evidence[:3]
        claim = Claim(
            text=f"Retrieved {len(bundle.evidence)} relevant evidence item(s).",
            evidence_ids=[item.evidence_id for item in citations],
            level=EvidenceLevel.SUPPORTED,
        )
        answer = AnswerResponse(
            answer_markdown="\n\n".join(
                ["Offline evidence summary:"] + [f"- {item.text[:240]}" for item in citations]
            ),
            claims=[claim],
            citations=citations,
            confidence=EvidenceLevel.SUPPORTED,
            limitations=["Generated by deterministic offline mode; no model synthesis was used."],
        )
        return self._publisher.validate(
            answer,
            allowed_evidence_ids=[item.evidence_id for item in bundle.evidence],
        )
