from typing import Any

models: Any

class AsyncQdrantClient:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def collection_exists(self, *args: Any, **kwargs: Any) -> bool: ...
    async def create_collection(self, *args: Any, **kwargs: Any) -> bool: ...
    async def get_collection(self, *args: Any, **kwargs: Any) -> Any: ...
    async def create_payload_index(self, *args: Any, **kwargs: Any) -> Any: ...
    async def upsert(self, *args: Any, **kwargs: Any) -> Any: ...
    async def scroll(self, *args: Any, **kwargs: Any) -> Any: ...
    async def delete(self, *args: Any, **kwargs: Any) -> Any: ...
    async def count(self, *args: Any, **kwargs: Any) -> Any: ...
    async def query_points(self, *args: Any, **kwargs: Any) -> Any: ...
    async def set_payload(self, *args: Any, **kwargs: Any) -> Any: ...
    async def close(self, *args: Any, **kwargs: Any) -> None: ...
