from collections.abc import Mapping
from types import TracebackType
from typing import Any, Self

class Record(Mapping[str, Any]):
    def __getitem__(self, key: str) -> Any: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...

class Transaction:
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool | None: ...

class Connection:
    def transaction(self) -> Transaction: ...
    async def execute(self, query: str, *args: Any) -> str: ...
    async def fetchrow(self, query: str, *args: Any) -> Record | None: ...
    async def fetch(self, query: str, *args: Any) -> list[Record]: ...

class PoolAcquireContext:
    async def __aenter__(self) -> Connection: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool | None: ...

class Pool:
    def acquire(self) -> PoolAcquireContext: ...
    async def close(self) -> None: ...
    async def execute(self, query: str, *args: Any) -> str: ...
    async def fetchrow(self, query: str, *args: Any) -> Record | None: ...
    async def fetch(self, query: str, *args: Any) -> list[Record]: ...

async def create_pool(
    dsn: str,
    *,
    min_size: int = ...,
    max_size: int = ...,
    command_timeout: int | float | None = ...,
) -> Pool: ...
